### PR TITLE
Support for Sublime Text 3

### PR DESCRIPTION
**Pull request by dnatag**
I take a liberal approach and disassemble the TodoRender class. Hope you don't mind.

### CODE REVIEW

**Comment by staticdreams** [comment]
Thanks mate! I cloned your version, it works great!

**Comment by robcowie** [comment]
Hey @dnatag thanks very much for your efforts. I have been thinking about ST3 support, and improvements I can make to performance and the code. I came to the conclusion that a rewrite is necessary. Of course, finding the time to do it is not easy.

I'll probably pull your changes in to a separate branch and make that available as ST3 compatibility if that's ok with you.

**Comment by dnatag** [comment]
Making current code base to be compatible with both ST2 and ST3 will be too much hassles. It is a great idea to have an independent ST3 branch.

**Comment by frizop** [comment]
This package seems to work for doing the open files, but fails in some cases for projects. 

Exception in thread Thread-4:
Traceback (most recent call last):
  File "X/threading.py", line 639, in _bootstrap_inner
  File "C:\Users\x\AppData\Roaming\Sublime Text 3\Packages\SublimeTODO\todo.py", line 270, in run
    formatted = list(self.format(todos))
  File "C:\Users\x\AppData\Roaming\Sublime Text 3\Packages\SublimeTODO\todo.py", line 282, in format
    messages = sorted(messages, key=key_func)
  File "C:\Users\x\AppData\Roaming\Sublime Text 3\Packages\SublimeTODO\todo.py", line 178, in extract
    for linenum, line in enumerate(f):
  File "X/codecs.py", line 300, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 0: invalid start byte

**Comment by dnatag** [comment]
@frizop
Thank you for point out the bug. On my mac, it is due to the .DS_Store file, which is supposed to be excluded. I have changed the match to search to overcome the problem. It fixes the issue on my Mac. Hopefully works for you too.

**Comment by frizop** [comment]
@dnatag ah thanks for the quick turn around on this, I imagine I've still got a little bit to figure out on my end, though I was able to fix it. I determined that one of my files had not been saved with UTF-8 formatting. As it turns out, after saving the encoding as UTF-8 in sublime the file no longer caused the plugin to fail. I wonder if you should catch the unicodeDecodeError. I'll fork and add this.

**Comment by jonathanrdelgado** [comment]
+1 for a ST3 Branch

**Comment by lmartins** [comment]
Hey, any updates on this?
Just changed to ST3 and im really missing this plugin.

Thanks.

**Comment by jonathanrdelgado** [comment]
@lmartins You can just use @dnatag's repo for now. Just clone it.

**Comment by lmartins** [comment]
@jonathandelgado I've tried that but I must be doing something wrong as it simply does nothing from that on. 
Im zipping the cloned files, adding the sublime extension and putting the file in the installed packages folder. Do I have to do anything else?

**Comment by jonathanrdelgado** [comment]
@lmartins Just clone it without zipping in the Packages folder.

**Comment by lmartins** [comment]
Thanks again.
I've managed to get it generating the menu options but sadly it won't generate any results. Guess i'll have to wait to the "official" release.

**Comment by dnatag** [comment]
@lmartins I think you need to delete the zip copy from the Installed Packages folder, otherwise ST3 load that copy first instead of the copy from Packages folder

**Comment by lmartins** [comment]
Thanks @dnatag, yes I did that before. Tried again on my laptop but got the same result. Perhaps it's interacting with some other plugin, not sure.

**Comment by lmartins** [comment]
Hi again, once I rebooted my computer it started to work. Thanks!  :-)

**Comment by lmartins** [comment]
Strangely, after rebooting my computer it is working now. Thanks!   

## 

Luis Martins
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by lmartins** [comment]
@dnatag There's an issue with your changes to SublimeTodo.
After many attempts to discover what was breaking Vintage mode in Sublime, i've discovered that it was your branch of SublimeTodo. With SublimeTodo installed, when i try to navigate up and down in Vintage Mode I always get "No Results to Navigate" on the status bar.

Any chance you could look into this?

**Comment by dnatag** [comment]
I updated three files. See if it fix your problem.

**Comment by lmartins** [comment]
@dnatag Yes, it's working fine now :-)
Thanks!

**Comment by robcowie** [comment]
Hey guys. I'm really sorry I've been silent about these issues. I'm afraid my new(ish) job and life have conspired against me. I have had very little time to work on this plugin.

I actually have a working version of the plugin for ST3, including some performance improvements. However, it is not really ready for release at this point. I also need to 'fix' the way I use settings. When I implemented this plugins I was not aware of the ability to store per-plugin settings outside of the global user settings file.

I'm also waiting for the release of the new version of Package Control. It will support different versions of plugins for different versions of ST. This will dictate how I release the new ST3 version; new branch or new repo.

In the short term however, I intend to find some time to pull in these changes and make an ST3 version available, though not via Package Control.

thanks for your efforts and your patience.
Rob

**Comment by laughedelic** [comment]
@robcowie any updates here?

**Comment by int3h** [comment]
@robcowie Could you push whatever you have currently to a new branch of this repo?

I'd be willing to help get the code up-to-shape, if I had access to the work-in-progress

**Comment by jonathanrdelgado** [comment]
@int3h He said he is busy and he'll get to it when he can. In the mean time, you can clone @dnatag's fork - I would consider it solid.

**Comment by thefirstofthe300** [comment]
@robcowie 

You were saying in the above that you were waiting for Package Control to update for compatibility with ST3.  It appears that they now have.

Here are the docs for ST3 plugin management.

https://sublime.wbond.net/docs/developers

**Comment by oleksandr-diudiun** [comment]
@dnatag Thanks man! I will tweet about your fork for Russian and Ukrainian teams

**Comment by zkwsk** [comment]
Thanks! The dnatag repo works great!

**Comment by Givemeyourgits** [comment]
I tried the latest version you have @dnatag but it freezes up sublime for me.  If I do it three times, it works once, but try it again and it freezes where it says Todo [= ](scanning 81 files).  Sometimes it works fine, sometimes it freezes.  Once it works, seems to work for that session, but another session it just freezes up.

**Comment by niklas-r** [comment]
This fork works for me but it seems that only user settings take effect and project settings are disregarded completely.

What I'm trying to do is adding some folder and file excludes using "folder_exclude_patterns" and "file_exclude_patters" as the documentation suggests. It only works however when I place it in my user settings and not my project settings. This is not a huge problem for me right now but it would be nice to have this working.

**Comment by lmartins** [comment]
Im having the same problem has @niklas-r , project level settings are completely ignored.

**Comment by jonathanrdelgado** [comment]
My final update to this:

TodoReview is now on Package Control. @robcowie has also handed over his spot in Package Control, so any active users with SublimeTODO installed will automatically be transferred over.

If you have any questions or issues, please submit an issue over at https://github.com/jonathandelgado/SublimeTodoReview.

Thank you.

**Pull request closed without merging**
