### PR TITLE
ST3 support, "Specific files only" functionality, improved TODO list navigation

### PR DESCRIPTION
**Pull request by plamen-nikolov**
I put together all changes that have been made so far by most of the forks, so you can merge them and bump the SublimeTODO version. We will be happy to see the updated version of SublimeTODO that supports ST3 and many new features. Thank you!

CHANGELOG:
- ST3 Support;
- "Specific files only" search functionality;
- Read settings from user settings file;
- "XXX" pattern match;
- TODOs in file menu;
- SublimeTODO preferences;

### CODE REVIEW

**Comment by lmartins** [comment]
At this point maybe it would make more sense to just open the plugin for the community as it is obvious the original maintainer doesn't have the time / disposition to maintain it anymore. 
Really missing this on ST3.

**Comment by thisislawatts** [comment]
Totally agree @lmartins, huge thanks to you @plamen-nikolov for putting this together. Only just realising how much I was missing this.

**Comment by jonathanrdelgado** [comment]
I'd be willing to maintain, @robcowie, if you are unable.

Kudos to @plamen-nikolov for the collection. However, upon further inspection, it looks like there are some issues with the PR. Settings don't seen to be used by the plugin correctly.

Next weekend i'll spend some time hammering the issues out.

**Comment by thisislawatts** [comment]
Hey @jonathandelgado I made a start on getting the settings back in there but I have not worked with python before, so would be great if you could take a look 1969e9b5886c07fd141549d1c88479729c29db89

Specifically I was wondering how this line worked, guessing it's ternary style shorthand trick?

```
settings['case_sensitive'] = 0 if plugin_settings.get('case_sensitive', False) else re.IGNORECASE
```

**Comment by jonathanrdelgado** [comment]
@thisislawatts Hey, I was going through fixing some of these today and just decided a rewrite would be the best option. I'll probably have a release this weekend.

In terms of your question, it's simply shorthand, as you guessed, which sets `case_sensitive` to `0` if the `get` function returns a false. Otherwise, it will go ahead and ignore the case.

**Comment by thisislawatts** [comment]
Great stuff, thanks for the answer. Looking through it I figured there was some tidying to be done, but I wasn't sure how to start

Be interested to see how it turns out.

**Comment by plamen-nikolov** [comment]
@thisislawatts Just propose your ideas and someone from us could help you.
How can we renew this package and put it again in the Package Manager's repo? Can we just create a new package, with different name, using this piece of code?

**Comment by plamen-nikolov** [comment]
So, as far as I can see, there is no progress with this PR, neither the repo. Thats why I've decided to create another repo - https://github.com/plamen-nikolov/DesiredTODO. Feel free to suggest any ideas, any PRs and everything you think will make this project useful and convenient for all of us. Lets make this tool the best one! Also, I will deploy it as a Sublime Package, so everyone can install it using Sublime Package Manager. 10x

**Comment by jonathanrdelgado** [comment]
Went ahead and fixed all the issues and added a bunch of features today. Here is the repo: https://github.com/jonathandelgado/SublimeTodoReview - currently in line to be added to Package Control - should be there tomorrow.
- Fixed Setting Issues
- Fixed Result Navigation Issues
- Added Color Scheme Support
- Added Priority Support
- Added Tag Support

More features coming soon.

Sorry @plamen-nikolov, would have sent you a PR, but just saw your repo.

**Comment by MintyOrb** [comment]
@jonathandelgado Was this put on package control? I don't see it there. Great work on it, by the way.

**Comment by jonathanrdelgado** [comment]
Hey @bornytm, I went ahead and requested it, but they are waiting for @robcowie to respond, since my version is a fork. Should be there within two weeks.

Here is the link so you can track it. https://github.com/wbond/package_control_channel/pull/2771 

Sorry for the delay, it's out of my hands.

**Comment by MintyOrb** [comment]
No worries, thanks!

**Comment by jonathanrdelgado** [comment]
My final update to this:

TodoReview is now on Package Control. @robcowie has also handed over his spot in Package Control, so any active users with SublimeTODO installed will automatically be transferred over.

If you have any questions or issues, please submit an issue over at https://github.com/jonathandelgado/SublimeTodoReview.

Thank you.

**Pull request closed without merging**
