### PR TITLE
Updated matching patterns

### PR DESCRIPTION
**Pull request by emilbayes**
After watching the video over at webdesign.tut+ I thought it would improve the UX of this project if the matching patterns ignored common comment endings.
I have also added the very common XXX to signal a warning

### CODE REVIEW

**Comment by emilbayes** [comment]
Also updated Readme.md to reflect changes I made in todo.py.
Please consider #1b7fe6a as this may cause fustration among users that FIXME and CHANGED can't have a space after the colon (unless this is intentionally)

**Comment by robcowie** [comment]
Nice idea, thanks.

I'm trying the patterns and they seem to miss loads of messages that should be matched. I'll try to find the time to pinpoint the problem; bit busy right now with work.

**Comment by emilbayes** [comment]
Can you give any examples? Then I'll try and solve it

**Comment by robcowie** [comment]
https://gist.github.com/2336769

Unless I'm being dim, the pattern changes cause non of the lines in that gist to be matched.

**Comment by pztrick** [comment]
I am using these patterns:

``` python
    'core_patterns': {

        'TODO': r'TODO[\s:]+(?P<todo>.*)$',

        'XXX': r'XXX[\s:]+(?P<xxx>.*)$',

        'NOTE': r'NOTE[\s:]+(?P<note>.*)$',

        'FIXME': r'FIX ?ME[\s:]+(?P<fixme>.*)$',

        'CHANGED': r'CHANGED[\s:]+(?P<changed>.*)$'

    },
```

And this is working well with matching either `# TODO: lorem ipsum` or `# TODO dolor sic amet` _(without the colon)_ -- though I'm not sure what additional functionality I may have lost in my tweaks.

**Comment by pkyeck** [comment]
:+1: for the optional colon. thanks.

**Comment by robcowie** [comment]
All development of this plugin has ceased and moved to https://github.com/jonathandelgado/SublimeTodoReview

**Pull request closed without merging**
